--[[
    init.lua
    Created: 03/11/2025 19:00:12
    Description: Autogenerated script file for the map dusty_dune.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'pmd_sunpath.GeneralFunctions'

-- Package name
local dusty_dune = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---dusty_dune.Init(zone)
--Engine callback function
function dusty_dune.Init(zone)


end

---dusty_dune.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function dusty_dune.EnterSegment(zone, rescuing, segmentID, mapID)


end

---dusty_dune.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function dusty_dune.ExitSegment(zone, result, rescue, segmentID, mapID)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> ExitSegment_dusty_dune (Dusty Dune) result "..tostring(result).." segment "..tostring(segmentID))
  GAME:SetRescueAllowed(false)

	--[[Different dungeon result typeS (cleared, died, etc)
	       public enum ResultType
        {
            Unknown = -1,
            Downed,
            Failed,
            Cleared,
            Escaped,
            TimedOut,
            GaveUp,
            Rescue
        }
		]]--
	if SV.ChapterProgression.Chapter == 1 then 
		if result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
			if SV.Chapter1.PlayerEnteredDune and not SV.Chapter1.PlayerCompletedDune then--player fainted before clearing
				GAME:EndDungeonRun(result, "sp_test_zone", -1, 9, 0, false, false)
				
				UI:SetSpeaker('', false, hero.CurrentForm.Species, hero.CurrentForm.Form, hero.CurrentForm.Skin, hero.CurrentForm.Gender)--set player as speaker 
				UI:SetSpeakerEmotion("Pain")
				UI:WaitShowDialogue("Ack...[pause=0] Got wiped out again...")			
	
				GAME:WaitFrames(20)
				
				GAME:EnterGroundMap("dusty_dune", "Main_Entrance_Marker")	

			else --failsafe
				print("error in resulting Sandy Dune completion")
			end
		else 
		
			if SV.Chapter1.PlayerEnteredDune and not SV.Chapter1.PlayerCompletedDune then--player made it through solo
				SV.Chapter1.PlayerCompletedDune = true	
				GAME:EnterGroundMap("abandoned_crossroads", "Main_Entrance_Marker")				
				
			else--failsafe 
				print("error in resulting Sandy Dune completion")
			end
		end		
	end
end

---dusty_dune.Rescued(zone, name, mail)
--Engine callback function
function dusty_dune.Rescued(zone, name, mail)


end

return dusty_dune

