--[[
    init.lua
    Created: 04/03/2025 19:57:36
    Description: Autogenerated script file for the map abandoned_crossroads.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'pmd_sunpath.PartnerEssentials'
require 'pmd_sunpath.ground.abandoned_crossroads.abandoned_crossroads_ch_1'

-- Package name
local abandoned_crossroads = {}

-------------------------------
-- Map Callbacks
-------------------------------
---abandoned_crossroads.Init(map)
--Engine callback function
function abandoned_crossroads.Init(map)


end

---abandoned_crossroads.Enter(map)
--Engine callback function
function abandoned_crossroads.Enter(map)

	abandoned_crossroads.PlotScripting()

end

---abandoned_crossroads.Exit(map)
--Engine callback function
function abandoned_crossroads.Exit(map)


end

---abandoned_crossroads.Update(map)
--Engine callback function
function abandoned_crossroads.Update(map)


end

---abandoned_crossroads.GameSave(map)
--Engine callback function
function abandoned_crossroads.GameSave(map)


end

function abandoned_crossroads.PlotScripting()
  --plot scripting
	if SV.ChapterProgression.Chapter == 1 then 
		if SV.Chapter1.PlayerCompletedDune then
			abandoned_crossroads_ch_1.Plot_Cutscene()
		end
	else
		GAME:FadeIn(20)
	end
end

---abandoned_crossroads.GameLoad(map)
--Engine callback function
function abandoned_crossroads.GameLoad(map)
	abandoned_crossroads.PlotScripting()
end


-------------------------------
-- Entities Callbacks
-------------------------------


return abandoned_crossroads

