--[[
    init.lua
    Created: 04/07/2025 12:23:10
    Description: Autogenerated script file for the map qahil_village.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'pmd_sunpath.PartnerEssentials'
require 'pmd_sunpath.ground.qahil_village_entrance.qahil_village_entrance_ch_1'

-- Package name
local qahil_village = {}

-------------------------------
-- Map Callbacks
-------------------------------
---qahil_village.Init(map)
--Engine callback function
function qahil_village.Init(map)


end

---qahil_village.Enter(map)
--Engine callback function
function qahil_village.Enter(map)

	qahil_village.StoryScripting()

end

---qahil_village.Exit(map)
--Engine callback function
function qahil_village.Exit(map)


end

---qahil_village.Update(map)
--Engine callback function
function qahil_village.Update(map)


end

---qahil_village.GameSave(map)
--Engine callback function
function qahil_village.GameSave(map)


end

function qahil_village.StoryScripting()
  --story scripting
	if SV.ChapterProgression.Chapter == 1 then 
		if not SV.Chapter1.PlayerAllowedInVillage then
			qahil_village_ch_1.Story_Cutscene()
		end
	else
		GAME:FadeIn(20)
	end
end

---qahil_village.GameLoad(map)
--Engine callback function
function qahil_village.GameLoad(map)

	qahil_village.StoryScripting()

end

-------------------------------
-- Entities Callbacks
-------------------------------


return qahil_village

