--[[
    init.lua
    Created: 02/28/2025 04:01:07
    Description: Autogenerated script file for the map test_map.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local test_map = {}

-------------------------------
-- Map Callbacks
-------------------------------
---test_map.Init(map)
--Engine callback function
function test_map.Init(map)


end

---test_map.Enter(map)
--Engine callback function
function test_map.Enter(map)

  GAME:FadeIn(20)

end

---test_map.Exit(map)
--Engine callback function
function test_map.Exit(map)


end

---test_map.Update(map)
--Engine callback function
function test_map.Update(map)


end

---test_map.GameSave(map)
--Engine callback function
function test_map.GameSave(map)


end

---test_map.GameLoad(map)
--Engine callback function
function test_map.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return test_map

