--[[
    init.lua
    Created: 02/27/2025 23:10:02
    Description: Autogenerated script file for the map dusty_dune.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'pmd_sunpath.PartnerEssentials'
require 'pmd_sunpath.ground.dusty_dune.dusty_dune_ch_1'

-- Package name
local dusty_dune = {}

-------------------------------
-- Map Callbacks
-------------------------------
---dusty_dune.Init(map)
--Engine callback function
function dusty_dune.Init(map)


end

---dusty_dune.Enter(map)
--Engine callback function
function dusty_dune.Enter(map)

	dusty_dune.StoryScripting()

end

---dusty_dune.Exit(map)
--Engine callback function
function dusty_dune.Exit(map)


end

---dusty_dune.Update(map)
--Engine callback function
function dusty_dune.Update(map)


end

---dusty_dune.GameSave(map)
--Engine callback function
function dusty_dune.GameSave(map)


end

---dusty_dune.GameLoad(map)
--Engine callback function
function dusty_dune.GameLoad(map)

end

function dusty_dune.StoryScripting()
  --Story scripting
	if SV.ChapterProgression.Chapter == 1 then 
		if not SV.Chapter1.PlayedIntroCutscene then --Opening Cutscene on a fresh save
			dusty_dune_ch_1.Intro_Cutscene()
		elseif SV.Chapter1.PlayerEnteredDune and not SV.Chapter1.PlayerCompletedDune then
			dusty_dune_ch_1.WipedInDune()
		end
	else 
		dusty_dune.GenericEnding()
	end
end

--No cutscene to play, play a generic ending saying there's nothing here.
function dusty_dune.GenericEnding()
	local hero = CH('PLAYER')
	local partner = CH('Teammate1')
	local partner2 = CH('Teammate2')
	local team2 = CH('Teammate2')
	local team3 = CH('Teammate3')

	AI:DisableCharacterAI(partner)
	AI:DisableCharacterAI(partner2)
	SOUND:StopBGM()
	GAME:WaitFrames(20)

	GAME:MoveCamera(235, 190, 1, false)
	GROUND:TeleportTo(hero, 240, 200, Direction.Up)
	GROUND:TeleportTo(partner, 272, 200, Direction.Up)
	GROUND:TeleportTo(partner2, 256, 232, Direction.Up)
	if team2 ~= nil then
		GROUND:TeleportTo(team2, 256, 232, Direction.Up)
	end
	if team3 ~= nil then
		GROUND:TeleportTo(team3, 288, 232, Direction.Up)
	end
	
	GAME:CutsceneMode(true)
	UI:ResetSpeaker()
	UI:WaitShowTitle(GAME:GetCurrentGround().Name:ToLocal(), 20)
	GAME:WaitFrames(60)
	UI:WaitHideTitle(20)
	GAME:FadeIn(40)
	
	SOUND:PlayBGM('In The Depths of the Pit.ogg', true)
	
	--numbers a bit wonk for camera and movement (not multiples of 2) to help match up with the slightly offcenter tablet and the other dusty dune scripts
	if SV.Chapter1.PlayerMetPartner and not SV.Chapter4.PlayerAndPartnerMetPartner2 then
		local coro1 = TASK:BranchCoroutine(function() GROUND:MoveToPosition(partner, 272, 200, false, 1) end)
		local coro2 = TASK:BranchCoroutine(function() GAME:WaitFrames(10)
												 	  GROUND:MoveToPosition(hero, 240, 200, false, 1) end)
		local coro3 = TASK:BranchCoroutine(function() if team2 ~= nil then GAME:WaitFrames(14) GROUND:MoveToPosition(team2, 256, 232, false, 1) end end)
		local coro4 = TASK:BranchCoroutine(function() if team3 ~= nil then GAME:WaitFrames(18) GROUND:MoveToPosition(team3, 288, 232, false, 1) end end)
		TASK:JoinCoroutines({coro1, coro2, coro3, coro4})
	else
		if SV.Chapter4.PlayerAndPartnerMetPartner2 then
			local coro1 = TASK:BranchCoroutine(function() GROUND:MoveToPosition(partner, 272, 200, false, 1) end)
			local coro2 = TASK:BranchCoroutine(function() GAME:WaitFrames(10)
												 	  	  GROUND:MoveToPosition(hero, 240, 200, false, 1) end)
			local coro3 = TASK:BranchCoroutine(function() GAME:WaitFrames(14)
												  	 	  GROUND:MoveToPosition(partner2, 256, 232, false, 1) end)
			local coro4 = TASK:BranchCoroutine(function() if team3 ~= nil then GAME:WaitFrames(18) GROUND:MoveToPosition(team3, 288, 232, false, 1) end end)
			TASK:JoinCoroutines({coro1, coro2, coro3, coro4})
		end
	end
	
	GAME:WaitFrames(10)	
	
	if SV.Chapter1.PlayerMetPartner and not SV.Chapter4.PlayerAndPartnerMetPartner2 then
		coro1 = TASK:BranchCoroutine(function() GeneralFunctions.LookAround(partner, 3, 4, false, false, true, Direction.Up) end)
		coro2 = TASK:BranchCoroutine(function() GAME:WaitFrames(10)
											    GeneralFunctions.LookAround(hero, 3, 4, false, false, true, Direction.Up) end)
		coro3 = TASK:BranchCoroutine(function() if team2 ~= nil then GAME:WaitFrames(14) GeneralFunctions.LookAround(team2, 3, 4, false, false, true, Direction.Up) end end)									  
		coro4 = TASK:BranchCoroutine(function() if team3 ~= nil then GAME:WaitFrames(18) GeneralFunctions.LookAround(team3, 3, 4, false, false, true, Direction.Right) end end)										  
		TASK:JoinCoroutines({coro1, coro2, coro3, coro4})
	else
		if SV.Chapter4.PlayerAndPartnerMetPartner2 then
			coro1 = TASK:BranchCoroutine(function() GeneralFunctions.LookAround(partner, 3, 4, false, false, true, Direction.Up) end)
			coro2 = TASK:BranchCoroutine(function() GAME:WaitFrames(10)
													GeneralFunctions.LookAround(hero, 3, 4, false, false, true, Direction.Up) end)
			coro3 = TASK:BranchCoroutine(function() GAME:WaitFrames(14)
													GeneralFunctions.LookAround(partner2, 3, 4, false, false, true, Direction.Up) end)								  
			coro4 = TASK:BranchCoroutine(function() if team3 ~= nil then GAME:WaitFrames(18) GeneralFunctions.LookAround(team3, 3, 4, false, false, true, Direction.Right) end end)										  
			TASK:JoinCoroutines({coro1, coro2, coro3, coro4})
		end
	end

	--temporary flags are set by the zone script rather than here.
	GAME:WaitFrames(20)
	UI:SetCenter(true)
	UI:WaitShowDialogue("There doesn't appear to be anything of interest here.")
	UI:WaitShowDialogue("It's impossible to go any further. It's time to go back.")
	GAME:WaitFrames(40)
	UI:SetCenter(false)
	SOUND:FadeOutBGM(60)
	GAME:FadeOut(false, 60)
	GAME:CutsceneMode(false)
	GAME:WaitFrames(20)
end

-------------------------------
-- Entities Callbacks
-------------------------------


return dusty_dune

