--[[
    init.lua
    Created: 04/04/2025 16:17:31
    Description: Autogenerated script file for the map qahil_village_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'pmd_sunpath.PartnerEssentials'
require 'pmd_sunpath.ground.qahil_village_entrance.qahil_village_entrance_ch_1'

-- Package name
local qahil_village_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---qahil_village_entrance.Init(map)
--Engine callback function
function qahil_village_entrance.Init(map)


end

---qahil_village_entrance.Enter(map)
--Engine callback function
function qahil_village_entrance.Enter(map)

	qahil_village_entrance.PlotScripting()

end

---qahil_village_entrance.Exit(map)
--Engine callback function
function qahil_village_entrance.Exit(map)


end

---qahil_village_entrance.Update(map)
--Engine callback function
function qahil_village_entrance.Update(map)


end

---qahil_village_entrance.GameSave(map)
--Engine callback function
function qahil_village_entrance.GameSave(map)


end

function qahil_village_entrance.PlotScripting()
  --plot scripting
	if SV.ChapterProgression.Chapter == 1 then 
		if SV.Chapter1.PlayerCompletedDune and not SV.Chapter1.PlayerEnteredVillage then
			qahil_village_entrnace_ch_1.Plot_Cutscene()
		end
	else
		GAME:FadeIn(20)
	end
end

---qahil_village_entrance.GameLoad(map)
--Engine callback function
function qahil_village_entrance.GameLoad(map)

	qahil_village_entrance.PlotScripting()

end

-------------------------------
-- Entities Callbacks
-------------------------------


return qahil_village_entrance

